### ISSUE TITLE
Breaking a block on the last use of your tool doesn't drop the correct item

### ISSUE THREAD

**Issue by I-Tom-I** [RhysB/Project-Poseidon#55] opened 2023-03-04 03:35 UTC
If you break a block that needs a certain tool to successfully drop it's item you will get nothing if that tool is on it's last use and breaks after mining the block.  The issue is that item breaking is handled earlier in the tick than determining drops.
The code that handles tools breaking is here https://github.com/RhysB/Project-Poseidon/blob/master/src/net/minecraft/server/ItemStack.java#L127 and the code that handles item drops for ores is here https://github.com/RhysB/Project-Poseidon/blob/master/src/net/minecraft/server/ItemPickaxe.java#L11 (there's other items that need tools to properly drop like shears on leaves, so those need fixing too)

**Comment by CodeKid0** [comment] 2023-03-07 06:07
I will try to reproduce and fix this. However, I'm not sure if it won't possibly create any duplication glitches?

**Comment by I-Tom-I** [comment] 2023-03-09 19:37
You can probably just backport a fix from a newer version of Minecraft

**Comment by Moresteck** [comment] 2023-03-09 20:47
Works as intended tbh. Unless you want it as an option, then sure

**Comment by RhysB** [comment] 2024-10-24 06:50
Resolved in https://github.com/RhysB/Project-Poseidon/commit/a6f02789d826e9b77ae4dddf16b4535f26aba2b5

**Closed by RhysB** 2024-10-24 06:50 UTC
Labels: bug, good first issue
